In [1]:
import sklearn as sk
from sklearn import datasets
import pandas as pd
import numpy as np
from scipy import sparse

[Write a Python program to load the iris data from a given csv file into a dataframe and print the shape of the data, type of the data and first 3 rows.](https://www.w3resource.com/machine-learning/scikit-learn/iris/python-machine-learning-scikit-learn-iris-basic-exercise-1.php)

In [3]:
df = pd.read_csv("iris.csv", delimiter="\t")
print(df.shape)
print(type(df))
df.head(3)

(150, 5)
<class 'pandas.core.frame.DataFrame'>


150    4  setosa  versicolor  virginica
0  5.1  3.5     1.4         0.2          0
1  4.9  3.0     1.4         0.2          0
2  4.7  3.2     1.3         0.2          0

[Write a Python program using Scikit-learn to print the keys, number of rows-columns, feature names and the description of the Iris data.](https://www.w3resource.com/machine-learning/scikit-learn/iris/python-machine-learning-scikit-learn-iris-basic-exercise-2.php)

In [9]:
print(df.keys())
print(df.shape)

Index(['150\t4\tsetosa\tversicolor\tvirginica'], dtype='object')
(150, 1)


[Write a Python program to get the number of observations, missing values and nan values.](https://www.w3resource.com/machine-learning/scikit-learn/iris/python-machine-learning-scikit-learn-iris-basic-exercise-3.php)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 1 columns):
 #   Column                             Non-Null Count  Dtype 
---  ------                             --------------  ----- 
 0   150	4	setosa	versicolor	virginica  150 non-null    object
dtypes: object(1)
memory usage: 1.3+ KB


[Write a Python program to create a 2-D array with ones on the diagonal and zeros elsewhere. Now convert the NumPy array to a SciPy sparse matrix in CSR format](https://www.w3resource.com/machine-learning/scikit-learn/iris/python-machine-learning-scikit-learn-iris-basic-exercise-4.php)

In [11]:
eye = np.eye(4)
print(eye)

sparse_matrix = sparse.csr_matrix(eye)
print(sparse_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


[]()

In [12]:
df.describe()

150\t4\tsetosa\tversicolor\tvirginica
count                                    150
unique                                   149
top                    5.8\t2.7\t5.1\t1.9\t2
freq                                       2